name: Validate

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:develop

    steps:
    - uses: actions/checkout@v2
    - name: Validation
      run: |
        cd src
        python3 -m plot_glm
    - name: Save results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: validate-result
        path: |
          validate.txt
